import Head from "next/head";
import Image from "next/image";

import LightGallery from "lightgallery/react";

// import styles
import "lightgallery/css/lightgallery.css";
import "lightgallery/css/lg-zoom.css";
import "lightgallery/css/lg-fullscreen.css";

// import plugins if you need
import lgZoom from "lightgallery/plugins/zoom";
import lgFullscreen from "lightgallery/plugins/fullscreen";

// styles
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

export default function Street() {
  const [items, setItems] = useState([]);

  const getData = async () => {
    const response = await fetch("/api/images/street");

    const data = await response.json();
    console.log("data", data);
    setItems(data);
  };

  useEffect(() => {
    getData();
  }, []);

  const onInit = () => {
    console.log("lightGallery has been initialized");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Street</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        Street
        <LightGallery
          onInit={onInit}
          speed={500}
          plugins={[lgZoom, lgFullscreen]}
          download={false}
        >
          {items.map((item: any) => {
            return (
              <a key={item.id + item.src} href={item.src}>
                <Image alt={" "} src={item.thumb} width={300} height={300} />
              </a>
            );
          })}
        </LightGallery>
      </main>
    </div>
  );
}
